receivers:
  prometheus:
    config:
      global:
        scrape_interval: 30s
      scrape_configs:
        - job_name: todo-service
          static_configs:
          - targets:
              - host.docker.internal:8080
            labels:
              job_name: todo-service

processors:
  batch:
    send_batch_size: 10000
    send_batch_max_size: 11000
    timeout: 10s

exporters:
  otlp:
    endpoint: "host.docker.internal:4317"
    tls:
      insecure: true
  logging:
    verbosity: detailed

service:
  pipelines:
    metrics:
      receivers: [prometheus]
      processors: [batch]
      exporters: [otlp, logging]
    #logs:
    #  receivers: [otlp]
    #  processors: [batch]
    #  exporters: [clickhouselogsexporter]